package com.wamogu.biz.auth.service;

import com.wamogu.biz.auth.convert.FwAccessCastor;
import com.wamogu.biz.auth.pojo.FwAccessDto;
import com.wamogu.biz.auth.pojo.FwAccessVo;
import com.wamogu.dao.repository.AccessRepository;
import com.wamogu.entity.auth.Access;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwAccessBizService extends BaseBizService<Access, FwAccessDto, FwAccessVo, Integer> {
    private final FwAccessCastor baseCastor;

    private final AccessRepository baseRepository;
}
