package com.wamogu.biz.auth.service;

import com.wamogu.biz.auth.convert.FwPrivilegeCastor;
import com.wamogu.biz.auth.pojo.FwPrivilegeDto;
import com.wamogu.biz.auth.pojo.FwPrivilegeVo;
import com.wamogu.dao.repository.PrivilegeRepository;
import com.wamogu.entity.auth.Privilege;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwPrivilegeBizService extends BaseBizService<Privilege, FwPrivilegeDto, FwPrivilegeVo, Integer> {
    private final FwPrivilegeCastor baseCastor;

    private final PrivilegeRepository baseRepository;

    public FwPrivilegeDto findByKey(String privilegeKey) {
        Privilege en = baseRepository.lambdaQuery()
                .eq(Privilege::getPrivilegeKey, privilegeKey)
                .one();
        return baseCastor.do2dto(en);
    }
}
