package com.wamogu.biz.auth.service;

import com.wamogu.biz.auth.convert.FwRoleCastor;
import com.wamogu.biz.auth.pojo.FwRoleDto;
import com.wamogu.biz.auth.pojo.FwRoleVo;
import com.wamogu.dao.repository.RoleRepository;
import com.wamogu.entity.auth.Role;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwRoleBizService extends BaseBizService<Role, FwRoleDto, FwRoleVo, Integer> {
    private final FwRoleCastor baseCastor;

    private final RoleRepository baseRepository;
}
