package com.wamogu.biz.auth.service;

import com.wamogu.biz.auth.convert.FwRoleCastor;
import com.wamogu.biz.auth.pojo.FwRoleDto;
import com.wamogu.biz.auth.pojo.FwRoleVo;
import com.wamogu.dao.repository.RoleRepository;
import com.wamogu.entity.auth.Role;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.Collection;
import java.util.List;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwRoleBizService extends BaseBizService<Role, FwRoleDto, FwRoleVo, Integer> {
    private final FwRoleCastor baseCastor;

    private final RoleRepository baseRepository;

    public FwRoleDto findByKey(String roleKey) {
        Role en = baseRepository.lambdaQuery()
                .eq(Role::getRoleKey, roleKey)
                .one();
        return baseCastor.do2dto(en);
    }

    public List<FwRoleDto> findByKeys(Collection<String> roleKeys) {
        List<Role> ens = baseRepository.lambdaQuery()
                .in(Role::getRoleKey, roleKeys)
                .list();
        return baseCastor.dos2dtos(ens);
    }
}
