package com.wamogu.biz.auth.service;

import com.wamogu.biz.auth.convert.FwUserCastor;
import com.wamogu.biz.auth.pojo.FwUserDto;
import com.wamogu.biz.auth.pojo.FwUserVo;
import com.wamogu.dao.repository.UserRepository;
import com.wamogu.entity.auth.User;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwUserBizService extends BaseBizService<User, FwUserDto, FwUserVo, Integer> {
    private final FwUserCastor baseCastor;

    private final UserRepository baseRepository;
}
