package com.wamogu.biz.gtd.service;

import com.wamogu.biz.gtd.convert.FwGtdTodoItemCastor;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemVo;
import com.wamogu.dao.repository.GtdTodoItemRepository;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwGtdTodoItemBizService extends BaseBizService<GtdTodoItem, FwGtdTodoItemDto, FwGtdTodoItemVo, Integer> {
    private final FwGtdTodoItemCastor baseCastor;

    private final GtdTodoItemRepository baseRepository;
}
