package com.wamogu.biz.gtd.service;

import com.wamogu.biz.gtd.convert.FwTodoItemCastor;
import com.wamogu.biz.gtd.pojo.FwTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwTodoItemVo;
import com.wamogu.dao.repository.TodoItemRepository;
import com.wamogu.entity.gtd.TodoItem;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-20
 */
@Getter
@Service
@RequiredArgsConstructor
public final class FwTodoItemBizService extends BaseBizService<TodoItem, FwTodoItemDto, FwTodoItemVo, Integer> {
    private final FwTodoItemCastor baseCastor;

    private final TodoItemRepository baseRepository;
}
