package com.wamogu.biz.gtd.service;

import com.wamogu.biz.gtd.convert.GtdTodoItemCastor;
import com.wamogu.biz.gtd.pojo.GtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.GtdTodoItemVo;
import com.wamogu.dao.repository.GtdTodoItemRepository;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.kit.BaseBizService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-05
 */
@Getter
@Service
@RequiredArgsConstructor
public final class GtdTodoItemBizService extends BaseBizService<GtdTodoItem, GtdTodoItemDto, GtdTodoItemVo, Integer> {
    private final GtdTodoItemCastor baseCastor;

    private final GtdTodoItemRepository baseRepository;
}
