package com.wamogu.biz.sys.service;

import com.wamogu.biz.sys.convert.SysConfigCastor;
import com.wamogu.biz.sys.pojo.SysConfigDto;
import com.wamogu.biz.sys.pojo.SysConfigVo;
import com.wamogu.dao.repository.SysConfigRepository;
import com.wamogu.entity.sys.SysConfig;
import com.wamogu.kit.BaseBizService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-02
 */
@Service
@RequiredArgsConstructor
public final class SysConfigBizService extends BaseBizService<SysConfig, SysConfigDto, SysConfigVo, Integer> {
    private final SysConfigCastor baseCastor;

    private final SysConfigRepository baseRepository;

    @Override
    public SysConfigCastor getBaseCastor() {
        return this.baseCastor;
    }

    @Override
    public SysConfigRepository getBaseRepository() {
        return this.baseRepository;
    }
}
