package com.wamogu.biz.gtd.convert;

import com.wamogu.biz.gtd.pojo.FwGtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemVo;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-13
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface FwGtdTodoItemCastor extends BaseCastor<GtdTodoItem, FwGtdTodoItemDto, FwGtdTodoItemVo> {
}
