package com.wamogu.biz.gtd.convert;

import com.wamogu.biz.gtd.pojo.FwTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwTodoItemVo;
import com.wamogu.entity.gtd.TodoItem;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-20
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface FwTodoItemCastor extends BaseCastor<TodoItem, FwTodoItemDto, FwTodoItemVo> {
}
