package com.wamogu.biz.gtd.convert;

import com.wamogu.biz.gtd.pojo.GtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.GtdTodoItemVo;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-02
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface GtdTodoItemCastor extends BaseCastor<GtdTodoItem, GtdTodoItemDto, GtdTodoItemVo> {
}
