package com.wamogu.rest.auth;

import com.wamogu.biz.auth.pojo.FwAccessDto;
import com.wamogu.biz.auth.pojo.FwAccessQuery;
import com.wamogu.biz.auth.pojo.FwAccessVo;
import com.wamogu.biz.auth.service.FwAccessBizService;
import com.wamogu.entity.auth.Access;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "AUTH-权限项表"
)
@RequestMapping("/access")
public final class FwAccessController extends BaseController<Access, FwAccessDto, FwAccessVo, FwAccessQuery, Integer> {
    private final FwAccessBizService bizService;
}
