/*
 * Falsework is a quick development framework
 * Copyright (C) 2015-2015 挖蘑菇技术部  https://tech.wamogu.com
 */
package com.wamogu.rest.auth;

import com.wamogu.biz.auth.pojo.FwPrivilegeDto;
import com.wamogu.biz.auth.pojo.FwPrivilegeQuery;
import com.wamogu.biz.auth.pojo.FwPrivilegeVo;
import com.wamogu.biz.auth.service.FwPrivilegeBizService;
import com.wamogu.entity.auth.Privilege;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 *
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(name = "AUTH-权限项表")
@RequestMapping("/privilege")
public final class FwPrivilegeController
        extends BaseController<Privilege, FwPrivilegeDto, FwPrivilegeVo, FwPrivilegeQuery, Integer> {

    private final FwPrivilegeBizService bizService;
}
