package com.wamogu.rest.auth;

import com.wamogu.biz.auth.pojo.FwRoleDto;
import com.wamogu.biz.auth.pojo.FwRoleQuery;
import com.wamogu.biz.auth.pojo.FwRoleVo;
import com.wamogu.biz.auth.service.FwRoleBizService;
import com.wamogu.entity.auth.Role;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "AUTH-角色表"
)
@RequestMapping("/role")
public final class FwRoleController extends BaseController<Role, FwRoleDto, FwRoleVo, FwRoleQuery, Integer> {
    private final FwRoleBizService bizService;
}
