package com.wamogu.rest.auth;

import com.wamogu.biz.auth.pojo.FwUserAuthMethodDto;
import com.wamogu.biz.auth.pojo.FwUserAuthMethodQuery;
import com.wamogu.biz.auth.pojo.FwUserAuthMethodVo;
import com.wamogu.biz.auth.service.FwUserAuthMethodBizService;
import com.wamogu.entity.auth.UserAuthMethod;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-13
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "AUTH-用户验证方式表"
)
@RequestMapping("/user_auth_method")
public final class FwUserAuthMethodController extends BaseController<UserAuthMethod, FwUserAuthMethodDto, FwUserAuthMethodVo, FwUserAuthMethodQuery, Integer> {
    private final FwUserAuthMethodBizService bizService;
}
