package com.wamogu.biz.sys.convert;

import com.wamogu.biz.sys.pojo.SysConfigDto;
import com.wamogu.biz.sys.pojo.SysConfigVo;
import com.wamogu.entity.sys.SysConfig;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-02
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface SysConfigCastor extends BaseCastor<SysConfig, SysConfigDto, SysConfigVo> {
}
