package com.wamogu.biz.sys.pojo;

import com.wamogu.querykit.FwQueryBase;
import com.wamogu.querykit.anno.FwQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-20
 */
@Data
@EqualsAndHashCode(
        callSuper = true
)
public final class FwOptionQuery extends FwQueryBase {
    @Schema(
            title = "key",
            description = "key"
    )
    @FwQuery
    private String optionKey;

    @Schema(
            title = "设置值",
            description = "设置值"
    )
    @FwQuery
    private String optionValue;

    @Schema(
            title = "自动加载",
            description = "自动加载"
    )
    @FwQuery
    private String autoload;

    @Schema(
            title = "id",
            description = "id"
    )
    @FwQuery
    private Integer id;

    @Schema(
            title = "创建人",
            description = "创建人"
    )
    @FwQuery
    private Integer createBy;

    @Schema(
            title = "最后更新人",
            description = "最后更新人"
    )
    @FwQuery
    private Integer updateBy;

    @Schema(
            title = "创建时间",
            description = "创建时间"
    )
    @FwQuery
    private LocalDateTime createTime;

    @Schema(
            title = "最后更新时间",
            description = "最后更新时间"
    )
    @FwQuery
    private LocalDateTime updateTime;
}
