server.servlet.context-path: /mgr/api

spring:
  devtools:
    restart:
      enabled: true
    add-properties: true
  application:
    name: falsework
    version: 0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.181.81:3306/tj_falsework
    username: usr_tjfw
    password: usr_tjfw_1234

logging:
  level:
    root: INFO
    com:
      wamogu: DEBUG
    org:
      springframework:
        web: DEBUG
      mybatis: DEBUG
  path: ./logs
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}[row:%line] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}[row:%line] %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
  file:
    name: logs/spring-log.log
  logback:
    rollingpolicy:
      max-history: 15
      max-file-size: 1MB

# mybatis-plus
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 生产环境

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wamogu

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# graceful
graceful-response:
  # exclude-packages:
  # exclude-return-types:
  default-validate-error-code: 400
  exclude-packages:
    - springfox.**
    - org.springframework.boot.actuate.*
  exclude-urls:
    - /**/v3/api-docs/*