package com.wamogu.rest.gtd;

import com.feiniaojin.gracefulresponse.api.ValidationStatusCode;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemQuery;
import com.wamogu.biz.gtd.pojo.FwGtdTodoItemVo;
import com.wamogu.biz.gtd.service.FwGtdTodoItemBizService;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.exception.ErrorKit;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "GTD-待办项"
)
@RequestMapping("/gtd_todo_item")
public final class FwGtdTodoItemController extends BaseController<GtdTodoItem, FwGtdTodoItemDto, FwGtdTodoItemVo, FwGtdTodoItemQuery, Integer> {
    private final FwGtdTodoItemBizService bizService;
}
