package com.wamogu.rest.gtd;

import com.wamogu.biz.gtd.pojo.FwTodoItemDto;
import com.wamogu.biz.gtd.pojo.FwTodoItemQuery;
import com.wamogu.biz.gtd.pojo.FwTodoItemVo;
import com.wamogu.biz.gtd.service.FwTodoItemBizService;
import com.wamogu.entity.gtd.TodoItem;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-20
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "GTD-待办项"
)
@RequestMapping("/todo_item")
public final class FwTodoItemController extends BaseController<TodoItem, FwTodoItemDto, FwTodoItemVo, FwTodoItemQuery, Integer> {
    private final FwTodoItemBizService bizService;
}
