package com.wamogu.rest.gtd;

import com.wamogu.biz.gtd.pojo.GtdTodoItemDto;
import com.wamogu.biz.gtd.pojo.GtdTodoItemQuery;
import com.wamogu.biz.gtd.pojo.GtdTodoItemVo;
import com.wamogu.biz.gtd.service.GtdTodoItemBizService;
import com.wamogu.entity.gtd.GtdTodoItem;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-02
 */
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "GTD-待办项"
)
@RequestMapping("/gtd_todo_item")
public final class GtdTodoItemController extends BaseController<GtdTodoItem, GtdTodoItemDto, GtdTodoItemVo, GtdTodoItemQuery, Integer> {
    private final GtdTodoItemBizService bizService;

    @Override
    public GtdTodoItemBizService getBizService() {
        return this.bizService;
    }
}
