/*
 * Falsework is a quick development framework
 * Copyright (C) 2015-2015 挖蘑菇技术部  https://tech.wamogu.com
 */
package com.wamogu.rest.sys;

import com.wamogu.biz.sys.pojo.*;
import com.wamogu.biz.sys.service.FwOptionBizService;
import com.wamogu.entity.sys.Option;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

/**
 * generated by FwUtilCodegen
 *
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(name = "系统配置")
@RequestMapping("/option")
public final class FwOptionController extends BaseController<Option, FwOptionDto, FwOptionVo, FwOptionQuery, Integer> {

    private final FwOptionBizService bizService;

    @Operation(description = "获得系统配置", summary = "获得系统配置")
    @GetMapping("/site")
    @Valid
    public SettingVo getSysSetting() {
        return getBizService().getSetting(SiteSettingDto.class).toVo();
    }

    @Operation(description = "保存系统配置", summary = "保存系统配置")
    @PostMapping("/site")
    @Valid
    public SettingVo setSysSetting(@RequestBody SiteSettingDto dto) {
        return getBizService().setSetting(dto).toVo();
    }
}
