package com.wamogu.rest.sys;

import com.wamogu.biz.sys.pojo.*;
import com.wamogu.biz.sys.service.FwOptionBizService;
import com.wamogu.entity.sys.Option;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Getter
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "系统配置"
)
@RequestMapping("/option")
public final class FwOptionController extends BaseController<Option, FwOptionDto, FwOptionVo, FwOptionQuery, Integer> {
    private final FwOptionBizService bizService;

    @GetMapping("/site")
    public SettingVo getSysSetting() {
        return getBizService().getSetting(SiteSettingDto.class).toVo();
    }
    @PostMapping("/site")
    public SettingVo setSysSetting(@RequestBody SiteSettingDto dto) {
        return getBizService().setSetting(dto).toVo();
    }
}
