package com.wamogu.rest.sys;

import com.wamogu.biz.sys.pojo.SysConfigDto;
import com.wamogu.biz.sys.pojo.SysConfigQuery;
import com.wamogu.biz.sys.pojo.SysConfigVo;
import com.wamogu.biz.sys.service.SysConfigBizService;
import com.wamogu.entity.sys.SysConfig;
import com.wamogu.kit.BaseController;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-02
 */
@ResponseBody
@RestController
@RequiredArgsConstructor
@Tag(
        name = "系统配置"
)
@RequestMapping("/sys_config")
public final class SysConfigController extends BaseController<SysConfig, SysConfigDto, SysConfigVo, SysConfigQuery, Integer> {
    private final SysConfigBizService bizService;

    @Override
    public SysConfigBizService getBizService() {
        return this.bizService;
    }
}
