package com.wamogu.biz.auth.pojo;

import com.wamogu.querykit.FwQueryBase;
import com.wamogu.querykit.anno.FwQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Data
@EqualsAndHashCode(
        callSuper = true
)
public final class FwAccessQuery extends FwQueryBase {
    @Schema(
            title = "权限项",
            description = "权限项"
    )
    @FwQuery
    private String accessKey;

    @Schema(
            title = "权限说明",
            description = "权限说明"
    )
    @FwQuery
    private String accessRemark;

    @Schema(
            title = "id",
            description = "id"
    )
    @FwQuery
    private Integer id;

    @Schema(
            title = "创建人",
            description = "创建人"
    )
    @FwQuery
    private Integer createBy;

    @Schema(
            title = "创建时间",
            description = "创建时间"
    )
    @FwQuery
    private LocalDateTime createTime;
}
