package com.wamogu.biz.auth.pojo;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Data
@Schema(
        title = "AUTH-权限项表 VO",
        description = "AUTH-权限项表 VO"
)
public final class FwAccessVo {
    @Schema(
            title = "权限项",
            description = "权限项"
    )
    private String accessKey;

    @Schema(
            title = "权限说明",
            description = "权限说明"
    )
    private String accessRemark;

    @Schema(
            title = "id",
            description = "id"
    )
    private Integer id;

    @Schema(
            title = "创建人",
            description = "创建人"
    )
    private Integer createBy;

    @Schema(
            title = "创建时间",
            description = "创建时间"
    )
    private LocalDateTime createTime;
}
