/*
 * Falsework is a quick development framework
 * Copyright (C) 2015-2015 挖蘑菇技术部  https://tech.wamogu.com
 */
package com.wamogu.biz.auth.pojo;

import com.wamogu.querykit.FwQueryBase;
import com.wamogu.querykit.anno.FwQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import java.util.Set;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * generated by FwUtilCodegen
 *
 * @since 2024-06-20
 */
@Data
@EqualsAndHashCode(callSuper = true)
public final class FwRoleQuery extends FwQueryBase {

    @Schema(title = "角色项(ROLE_开头)", description = "角色项(ROLE_开头)")
    @FwQuery
    private String roleKey;

    @Schema(title = "角色说明", description = "角色说明")
    @FwQuery
    private String roleRemark;

    @Schema(title = "权限项", description = "权限项")
    @FwQuery
    private Set<String> privileges;

    @Schema(title = "id", description = "id")
    @FwQuery
    private Integer id;

    @Schema(title = "创建人", description = "创建人")
    @FwQuery
    private Integer createBy;

    @Schema(title = "最后更新人", description = "最后更新人")
    @FwQuery
    private Integer updateBy;

    @Schema(title = "创建时间", description = "创建时间")
    @FwQuery
    private LocalDateTime createTime;

    @Schema(title = "最后更新时间", description = "最后更新时间")
    @FwQuery
    private LocalDateTime updateTime;
}
