/*
 * Falsework is a quick development framework
 * Copyright (C) 2015-2015 挖蘑菇技术部  https://tech.wamogu.com
 */
package com.wamogu.biz.auth.pojo;

import com.wamogu.enums.UserIdentifyType;
import com.wamogu.querykit.FwQueryBase;
import com.wamogu.querykit.anno.FwQuery;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * generated by FwUtilCodegen
 *
 * @since 2024-06-20
 */
@Data
@EqualsAndHashCode(callSuper = true)
public final class FwUserAuthMethodQuery extends FwQueryBase {

    @Schema(title = "用户id", description = "用户id")
    @FwQuery
    private Integer uid;

    @Schema(title = "验证方式", description = "验证方式")
    @FwQuery
    private UserIdentifyType type;

    @Schema(title = "参数1", description = "参数1")
    @FwQuery
    private String param1;

    @Schema(title = "参数2", description = "参数2")
    @FwQuery
    private String param2;

    @Schema(title = "是否禁用", description = "是否禁用")
    @FwQuery
    private boolean disabled;

    @Schema(title = "id", description = "id")
    @FwQuery
    private Integer id;

    @Schema(title = "创建人", description = "创建人")
    @FwQuery
    private Integer createBy;

    @Schema(title = "最后更新人", description = "最后更新人")
    @FwQuery
    private Integer updateBy;

    @Schema(title = "创建时间", description = "创建时间")
    @FwQuery
    private LocalDateTime createTime;

    @Schema(title = "最后更新时间", description = "最后更新时间")
    @FwQuery
    private LocalDateTime updateTime;
}
