package com.wamogu.biz.auth.pojo;

import com.wamogu.po.UserProps;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import java.util.Set;
import lombok.Data;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Data
@Schema(
        title = "FwUserDto",
        description = "FwUserDto"
)
public final class FwUserDto {
    @Schema(
            title = "用户名",
            description = "用户名"
    )
    private String username;

    @Schema(
            title = "名",
            description = "名"
    )
    private String givenName;

    @Schema(
            title = "姓",
            description = "姓"
    )
    private String familyName;

    @Schema(
            title = "昵称",
            description = "昵称"
    )
    private String nickName;

    @Schema(
            title = "密码",
            description = "密码"
    )
    private String pwd;

    @Schema(
            title = "是否启用",
            description = "是否启用"
    )
    private boolean enabled;

    @Schema(
            title = "用户属性",
            description = "用户属性"
    )
    private UserProps props;

    @Schema(
            title = "accesses",
            description = "accesses"
    )
    private Set accesses;

    @Schema(
            title = "roles",
            description = "roles"
    )
    private Set roles;

    @Schema(
            title = "identifications",
            description = "identifications"
    )
    private Set identifications;

    @Schema(
            title = "id",
            description = "id"
    )
    private Integer id;

    @Schema(
            title = "创建人",
            description = "创建人"
    )
    private Integer createBy;

    @Schema(
            title = "最后更新人",
            description = "最后更新人"
    )
    private Integer updateBy;

    @Schema(
            title = "创建时间",
            description = "创建时间"
    )
    private LocalDateTime createTime;

    @Schema(
            title = "最后更新时间",
            description = "最后更新时间"
    )
    private LocalDateTime updateTime;
}
