package com.wamogu.biz.auth.convert;

import com.wamogu.biz.auth.pojo.FwAccessDto;
import com.wamogu.biz.auth.pojo.FwAccessVo;
import com.wamogu.entity.auth.Access;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface FwAccessCastor extends BaseCastor<Access, FwAccessDto, FwAccessVo> {
}
