/*
 * Falsework is a quick development framework
 * Copyright (C) 2015-2015 挖蘑菇技术部  https://tech.wamogu.com
 */
package com.wamogu.biz.auth.convert;

import com.wamogu.biz.auth.pojo.FwPrivilegeDto;
import com.wamogu.biz.auth.pojo.FwPrivilegeVo;
import com.wamogu.entity.auth.Privilege;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 *
 * @since 2024-06-20
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface FwPrivilegeCastor extends BaseCastor<Privilege, FwPrivilegeDto, FwPrivilegeVo> {}
