package com.wamogu.biz.auth.convert;

import com.wamogu.biz.auth.pojo.FwRoleDto;
import com.wamogu.biz.auth.pojo.FwRoleVo;
import com.wamogu.entity.auth.Role;
import com.wamogu.kit.BaseCastor;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * generated by FwUtilCodegen
 * @since 2024-06-12
 */
@Mapper(
        componentModel = "spring",
        uses = {},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface FwRoleCastor extends BaseCastor<Role, FwRoleDto, FwRoleVo> {
}
